### ISSUE TITLE
Review: 61

### ISSUE THREAD

**Issue by Nicsteg** [Team-Octagon/voluntree#61]
## Overview

The focus for this code review will be centered around the _____ page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-061

## Files to review

* [app/imports/api/event/EventCollection.js](https://github.com/Team-Octagon/voluntree/blob/issue-027/app/imports/api/event/Events.js)
* https://github.com/Team-Octagon/voluntree/blob/main/app/imports/ui/components/VolunteerEventDash.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](https://github.com/cammoore/414-review-checklists/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/414-review-checklists/blob/main/checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

11:30 pm, Monday, Januray 29th

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by connorn-dev** [comment]
## EventCollection.js: 
✅ Architecture 
 Design 01: Lines 98-134 can potentially be refactored to avoid repetative if statements. 
✅ JS
✅ React

## VounteerEventDash.js
✅ Architecture 
Design 05: Comments should be added, unsure what code is doing from a glance.
Design 07: Not required but onChange on line 17 could be separate named function. 
✅ JS
✅ React

Overall, I think these minor changes can help the readability and get us used to doing code reviews on our code.

**Comment by jligeral** [comment]
## EventCollection.js
- No comment on this

##VolunteerEventDash.js
- Design 05 L21: I think the comment is trivial

**Comment by Nicsteg** [comment]
## EventCollection.js: 
Architecture looks good
Design 01: Lines 88-134 could be shortened or less if statements? 
Javascript looks good no lint errors
Meteor Checklist looks good

Additional comments, did we want a skills area for the event that are required 

## VounteerEventDash.js
Architecture looks good
Design-01: The search function may be used as another component in case it needs to be used for multiple pages
Design-05: 0 comments maybe something about what the code does.
Javascript looks good no lint errors
Meteor Checklist looks good
REACT-01: search function may be component?
TEST-ACCEPTANCE-01: do we have this?

Overall code looks good some minor changes to be made!

**Comment by micahtilton** [comment]
## EventCollection.js:
- [x] Architecture Checklist 
- [x] Design Checklist
  - L17 Design-05: Ensure comments are appropriate. Add comments to avoid confusion
- [x] JS Checklist
- [x] Meteor Checklist
- [x] React Checklist
- [x] Testing Checklist
  - No testing to assure that page is being loaded

## VounteerEventDash.js:
- [x] Architecture Checklist 
- [x] Design Checklist
  - L7 Design-05: Ensure comments are appropriate. Add comments to avoid confusion
- [x] JS Checklist
- [x] Meteor Checklist
- [x] React Checklist
  - L14 REACT-07: Don't retrieve collection data inside render(). Fix this when mongo collection is created
- [x] Testing Checklist
  - No testing to assure that page is being loaded

**Comment by jligeral** [comment]
> ## EventCollection.js:
> Additional comments, did we want a skills area for the event that are required

There's a separate directory for it if you look.

**Comment by Nicsteg** [comment]
Outcome of review meeting

New Issues: 

- Create an issue to add testing to the events collection
- Create an issue to add testing to the volunteer event dash
- Create an issue to make a search function component
- Create an issue to update VounteerEventDash once the Mongo database is working with collections

Other Issues: 

- make sure other pages have Mongo database integration for when our collections are finished
- add testing to other pages as well

**Comment by bing-ying-li** [comment]
EventCollection.js
Architecture Checklist✅
Design Checklist✅
JS Checklist✅
Meteor Checklist✅
React Checklist✅
VounteerEventDash.js
Architecture Checklist✅
Design Checklist✅
JS Checklist✅
Meteor Checklist✅
React Checklist✅
