### ISSUE TITLE
Review: Review 2 meeting

### ISSUE THREAD

**Issue by Nicsteg** [Team-Octagon/voluntree#76]
## Overview

The focus for this code review will be centered around the _____ page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-076

## Files to review

* [app/imports/ui/components/VolunteerProfileDash.jsx](https://github.com/Team-Octagon/voluntree/blob/main/app/imports/ui/components/VolunteerProfileDash.jsx)
* [app/imports/ui/components/EventCardTest.jsx](https://github.com/Team-Octagon/voluntree/blob/main/app/imports/ui/components/EventCardTest.jsx)

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

Monday, February 5th at 11:30 pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by Nicsteg** [comment]
## [app/imports/ui/components/VolunteerProfileDash.jsx](https://github.com/Team-Octagon/voluntree/blob/main/app/imports/ui/components/VolunteerProfileDash.jsx)
Architecture looks good
Design 01: I would move the test code into a new file or update it to use the existing data that we have by now
Javascript looks good no lint errors
Meteor Checklist looks good

Additional comments, did we want a skills area for the event that are required 

## [app/imports/ui/components/EventCardTest.jsx](https://github.com/Team-Octagon/voluntree/blob/main/app/imports/ui/components/EventCardTest.jsx)
Architecture looks good
Design-01: I would make the name more unique instead of test because its not descriptive
Design-05: 0 comments maybe something about what the code does.
Javascript: {tags.map((tag, index) => (
        <Badge key={index} variant="info" className="m-1">
          {tag} was giving some lint warnings
Meteor Checklist looks good

Overall code looks good some minor changes to be made!

**Comment by connorn-dev** [comment]
## VolunteerProfileDash.jsx
✅ Architecture
Design-04: Test code will eventually get moved out..
✅ JS
React-04: Consider adding proptypes for VoulenteerProfileDash and EventCard when we use database.
Testing-01: Testing will need to be implemented. 

Additional: Data validation for tags should be added at some point. 

## EventCardTest.jsx

✅ Architecture
✅ Design
✅ JS
✅ React
✅ Testing-01: Testing will need to be implemented. 

Additional: Alt props should be added for the image in EventCardTest.

**Comment by micahtilton** [comment]
## VolunteerProfileDash.jsx:
- [x] Architecture Checklist 
- [x] Design Checklist
- [x] JS Checklist
- [x] Meteor Checklist
- [x] React Checklist
  - L68 : Eventually the key should be the event id
- [x] Testing Checklist
  - Testing needs to be done for this page

## EventCardTest.jsx:
- [x] Architecture Checklist 
  - EventCardTest name may cause confusion. Is this component going to replace EventCard in the future? Maybe it can be renamed
- [x] Design Checklist
- [x] JS Checklist
- [x] Meteor Checklist
- [x] React Checklist
  - L5 : In the future, this component should only take in an event as input
- [x] Testing Checklist
  - This is a component which does not need testing

**Comment by Nicsteg** [comment]
Outcome of review meeting

New Issues:

Create an issue to Move out the test code for Volunteerprofiledash and use database data
Create an issue to add testing to the Volunteerprofiledash

Other Issues:

make sure other pages have Mongo database integration for when our collections are finished
add testing to other pages as well

**Comment by bing-ying-li** [comment]
VolunteerProfileDash.jsx
 Architecture Checklist✅
 Design Checklist✅
 JS Checklist✅
 Meteor Checklist✅
 React Checklist：Testing Checklist：Check if the component is properly tested, either through unit tests or integration tests.

EventCardTest.jsx
 Architecture Checklist✅
 Design Checklist✅
 JS Checklist✅
 Meteor Checklist✅
 React Checklist✅

**Comment by DelsinRhoney** [comment]
VolunteerProfileDash.jsx
Architecture Checklist✅
Design Checklist✅
JS Checklist✅
Meteor Checklist✅
React Checklist：✅
Testing Checklist：✅

EventCardTest.jsx
Architecture Checklist✅
Design Checklist✅
JS Checklist✅
Meteor Checklist✅
React Checklist✅
